name: Aakar
favicon: null
layout_spectrum: 0.02369
typography_spectrum: 0.84834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000017'
    - '#f5ffff'
    - '#fa924a'
    - '#848760'
    - '#922d14'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
