name: Aakar
favicon: null
layout_spectrum: 0.5072247316129506
typography_spectrum: 0.4411464862059802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9390022410079837
  lightness: 0.38523317920044065
  saturation: 0.4488029587082565
  rhythmicContrast: 0.8745584203861654
purpose: []
