name: Aakar
favicon: null
layout_spectrum: 0.79042
typography_spectrum: 0.84834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#507aa8'
    - '#00020f'
    - '#fbba6f'
    - '#fa7c0c'
    - '#7f543e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
